### ISSUE TITLE
Insecure Response

### ISSUE THREAD

**Issue by spaced-out-factory** [humanmade/wp-stripe#23]
When adding the shortcode in Chrome the content for the popup fails to load.

GET https://shekinahgloryfire.com/?wp-stripe-iframe=true&keepThis=true& net::ERR_INSECURE_RESPONSE 

http://shekinahgloryfire.com/donate/

**Comment by willmot** [comment]
I assume that's because your site isn't available over HTTPS? I get the following warning when visiting https://shekinahgloryfire.com/

![screen shot 2014-07-10 at 20 40 15](https://cloud.githubusercontent.com/assets/308507/3544189/05cf305c-086a-11e4-8c55-d863d10bf725.png)

You'll want to either get your site working over HTTPS or disable the "Enable SSL for modal pop-up?" option.

**Comment by spaced-out-factory** [comment]
Thanks that solved the problem.
